### ISSUE TITLE
Am I Proplery Authenticating Using the CLI When Uploading a Manifest to a Dataset I Own?

### ISSUE THREAD

**Issue by aaronm-2112** [Pennsieve/pennsieve-agent#5]
Occasionally, when trying to upload a manifest to a dataset I own, I have issues with attaining authorization to perform the upload. When following ( what I think are )  the normal steps to fix this issue - reauthorizing the user profile - it will persist.  The only measure I've found that works consistently for regaining authorization in these instances is to delete the .pennsieve folder, re-run the config wizard, and then resume uploads again.

Here are the steps I follow when uploading a manifest to a dataset with the Agent (assuming a dataset I have access to has already been selected via pennsieve dataset use ):
pennsieve agent 
pennsieve profile reauth 
pennsieve dataset use dataset_id
pennsieve manifest create -path-to-dataset
pennsieve upload manifest manifest_id

Here is the agent's output after failing to authorize: 

2022/10/03 11:49:33 Server starting upload manifest 3
2022/10/03 11:49:33 Getting manifest with ID:  3
2022/10/03 11:49:33 MANIFEST SYNC
2022/10/03 11:49:33 SELECT * FROM manifest_files WHERE manifest_id = ? AND status IN ('Local','Changed','Failed','Removed','Imported','Finalized','Unknown') ORDER BY id LIMIT ? OFFSET ?
2022/10/03 11:49:33 NUMBER OF RECORDS:  250
2022/10/03 11:49:34 Unauthorized
2022/10/03 11:49:34 Unable to synchronize manifest with Server, cancelling uploading.

Perhaps I am missing/misunderstanding some authorization step I need the agent to perform in order to upload after seeing the Unauthorized message? 

Addendum:
OS: Ubuntu 20.04.4 LTS

Thanks!

**Comment by jwagenaar** [comment]
Hi, 
I would expect this to work with the latest version of the agent. Please contact us by email if you are still encountering this issue. Thanks!
